# Generated by Django 2.2.5 on 2019-11-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=8)),
                ('photo', models.ImageField(upload_to='images')),
            ],
        ),
    ]
