# Generated by Django 2.2.5 on 2019-11-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_jobdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
