# Generated by Django 2.2.5 on 2019-11-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191107_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='image',
            field=models.ImageField(upload_to='jobimages/'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
